logging:
    config: classpath:logback.xml
xxl:
    job:
        accessToken: ''
        admin:
            addresses: http://192.168.200.129:8093/xxl-job-admin
        executor:
            address: ''
            appname: cai-stock-executor
            ip: ''
            logpath: ./logs
            logretentiondays: 30
            port: 7979
